title: Xing Du # your name (or website title) here
logo: "/images/logo2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MSCS @ NEU, AMTS Software Engineer @ Salesforce
  <br><br>
  Email: xingdu1991@gmail.com
#  <br><br>
#  <a href="https://github.com/xingdu1991/xingdu1991.github.io/blob/master/pdf/XingDu_Resume_2020.pdf">Resume<a/>
  <br><br>
  <a href="https://www.linkedin.com/in/xingdu1991/">LinkedIn</a>

theme: jekyll-theme-minimal
google_analytics: UA-85802011-1 # your Google Analytics tracking ID here
