title: Xing Du # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  CS Graduate @ Northeaster University
  <br><br>
  Software Engineer Intern @ Salesforce
  <br><br>
  <a href="https://www.linkedin.com/in/xingdu1991/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://github.com/chinadd">View My Github Profile</a>
  <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
